# -*- coding: utf-8 -*-
"""Interactive science quiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dawGWoGFhp_1-qkcZFN55JOoMKrRyjgw
"""

import random

# Define questions
questions = [
    {
        "question": "What is the smallest planet in our solar system?",
        "options": ["Mercury", "Venus", "Mars", "Jupiter"],
        "answer": "Mercury",
    },
    {
        "question": "What is the largest planet in our solar system?",
        "options": ["Mercury", "Venus", "Mars", "Jupiter"],
        "answer": "Jupiter",
    },
    {
        "question": "What is the hottest planet in our solar system?",
        "options": ["Mercury", "Venus", "Mars", "Jupiter"],
        "answer": "Venus",
    },
    {
        "question": "What is the coldest planet in our solar system?",
        "options": ["Mercury", "Venus", "Mars", "Neptune"],
        "answer": "Neptune",
    },
]

# Define quiz function
def quiz():
    score = 0
    for question in questions:
        print(f"\nQuestion: {question['question']}")
        random.shuffle(question["options"])
        for option in question["options"]:
            print(f"{option}")
        answer = input("Enter your answer: ")
        if answer.lower() == question["answer"].lower():
            print("Correct!")
            score += 1
        else:
            print(f"Incorrect. The correct answer is {question['answer']}.")
    print(f"\nYour score is {score}/{len(questions)}")
    retake = input("Would you like to try again? (y/n) ")
    if retake.lower() == 'y':
      quiz()
    else:
      print("Thank you for attempting the quiz")

# Call quiz function
quiz()

